### ISSUE TITLE
Create GUI For The Converter.

### ISSUE THREAD

**Issue by BJTMastermind** [BJTMastermind/Indev-To-Infdev-World-Converter#10]
Add a GUI for the converter as all the conversion functions are almost finished.

Concept design:
![converter](https://user-images.githubusercontent.com/18742837/139779000-50164a39-f382-4786-b0a5-325558696354.png)

**Comment by VoxelBill** [comment]
Possible Finished GUI for the converter.
![converter_gui](https://user-images.githubusercontent.com/18742837/140423681-3219e011-df63-4e50-a2bc-313f0948fe30.png)
