### ISSUE TITLE
please can I have the jar :(

### ISSUE THREAD

**Issue by Loweredgames** [BJTMastermind/Indev-To-Infdev-World-Converter#13]
I need it to convert maps

**Comment by Loweredgames** [comment]
@BJTMastermind

**Comment by VoxelBill** [comment]
Ok just as a disclaimer so you know this project is unfinished and only supports converting to Minecraft Alpha currently if you want the worlds in newer versions like Beta or 1.12+ you will have to bring the Alpha world through a few different versions to get it there without it getting corrupted. Also there are lots of bugs still like the lighting not being fixed so the world is completely dark for awhile and also causes a lot of lag to the point of the game crashing from it all updating in game. But if all that is fine for you I guess I can give the jar file if you want it as im currently stuck on trying to figure out the lighting thing.

**Comment by VoxelBill** [comment]
@Loweredgames If you are still want the jar with the disclaimers i mentioned let me know and ill send the file here.

**Comment by VoxelBill** [comment]
As no response was given in 2 weeks this issue will be closed and no jar file will be posted.
