### ISSUE TITLE
Add Support For Converting From Pre-Classic

### ISSUE THREAD

**Issue by BJTMastermind** [BJTMastermind/Indev-To-Infdev-World-Converter#6]
Add Support for Pre Classic Versions

**Comment by VoxelBill** [comment]
A separate library will have to be made to handle Pre-Classic / Classic worlds

**Comment by BJTMastermind** [comment]
The above will not be needed now.

**Comment by VoxelBill** [comment]
This feature has been canceled as there is no good way of reading the world data of pre-classic worlds.
If a way of supporting multiple versions of pre-classic is found in the future I might make a separate program for pre-classic/classic to indev.
