### ISSUE TITLE
Add Support For Converting From Classic

### ISSUE THREAD

**Issue by BJTMastermind** [BJTMastermind/Indev-To-Infdev-World-Converter#7]
Add Support for Converting All Classic Versions

- [ ] Early Classic Creative
- [ ] Multiplayer Test
- [ ] Survival Test
- [ ] Late Classic Creative

**Comment by VoxelBill** [comment]
A separate library will have to be made to handle Pre-Classic / Classic worlds

**Comment by BJTMastermind** [comment]
The above will not be needed now.

**Comment by VoxelBill** [comment]
This feature has been canceled as it would be very hard to support multiple versions of classic at the moment.
If a better way of supporting multiple versions of classic is found in the future I might make a separate program for pre-classic/classic to indev.
